import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const URL=Deno.env.get("SUPABASE_URL")??""; const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const STAFF=["ozk.kh@outlook.com","khalelkhallouf1196@gmail.com"];
const AGENTS=["ozkkhalouf@gmail.com"];
const allowed=new Set(["health","stock","customers"]);
function headers(req:Request){const o=req.headers.get("origin")??"";const ok=["https://ozktobacco.com","https://www.ozktobacco.com"].includes(o)||o.startsWith("http://localhost");return {"Access-Control-Allow-Origin":ok?o:"https://ozktobacco.com","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Vary":"Origin"};}
function json(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:headers(req)});}
async function user(req:Request){const auth=req.headers.get("authorization")??"";if(!auth.startsWith("Bearer "))throw new Error("unauthorized");const r=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:KEY,Authorization:auth}});if(!r.ok)throw new Error("unauthorized");const u=await r.json();return {id:String(u.id),email:String(u.email??"").toLowerCase()};}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}});if(!r.ok)throw new Error(`data_${r.status}_${await r.text()}`);const t=await r.text();return t?JSON.parse(t):null;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});if(req.method!=="POST")return json(req,405,{error:"method_not_allowed"});try{const u=await user(req);const b=await req.json().catch(()=>({}));const action=String(b.action??"");
if(action==="request"){if(!STAFF.includes(u.email))throw new Error("forbidden");const resource=String(b.resource??"");if(!allowed.has(resource))return json(req,400,{error:"unsupported_resource"});const rows=await rest("ameen_read_requests",{method:"POST",body:JSON.stringify({requested_by:u.id,resource})});return json(req,200,{id:rows?.[0]?.id,status:"pending"});}
if(action==="status"){if(!STAFF.includes(u.email))throw new Error("forbidden");const id=encodeURIComponent(String(b.id??""));const rows=await rest(`ameen_read_requests?id=eq.${id}&requested_by=eq.${u.id}&select=id,resource,status,requested_at,completed_at,expires_at,response,error,agent_id&limit=1`);return json(req,200,{request:rows?.[0]??null});}
if(action==="poll"){if(!AGENTS.includes(u.email))throw new Error("forbidden");const now=encodeURIComponent(new Date().toISOString());const rows=await rest(`ameen_read_requests?status=eq.pending&expires_at=gt.${now}&order=requested_at.asc&limit=1`);const job=rows?.[0]??null;if(job)await rest(`ameen_read_requests?id=eq.${job.id}&status=eq.pending`,{method:"PATCH",body:JSON.stringify({status:"processing",claimed_at:new Date().toISOString(),agent_id:u.email})});return json(req,200,{job:job?{id:job.id,resource:job.resource}:null});}
if(action==="complete"){if(!AGENTS.includes(u.email))throw new Error("forbidden");const id=encodeURIComponent(String(b.id??""));const ok=b.ok===true;await rest(`ameen_read_requests?id=eq.${id}&status=eq.processing`,{method:"PATCH",body:JSON.stringify({status:ok?"completed":"failed",completed_at:new Date().toISOString(),response:ok?b.response:null,error:ok?null:String(b.error??"gateway_failed"),agent_id:u.email})});return json(req,200,{ok:true});}
return json(req,400,{error:"unsupported_action"});}catch(e){const m=String(e?.message??"internal_error");return json(req,m==="unauthorized"?401:m==="forbidden"?403:500,{error:m});}});
